name: Build and Deploy CV

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest # Directly specify the runner
    name: Build CV for GitHub Pages # Simplified name
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Nix
        # Build the default package for the runner's system
        run: nix build . --out-link ./result-gh-pages
      - name: List build output
        run: ls -la ./result-gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result-gh-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
