name: Build and Deploy CV

on:
  push:
    branches: [ master ] 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build CV HTML with Nix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Nix
        run: nix build .#resume --out-link ./result-build # Build the 'resume' package from flake.nix
      - name: Rename HTML for GitHub Pages
        run: mv ./result-build/resume.html ./result-build/index.html # Assumes make creates resume.html in the $out dir
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result-build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
